### ISSUE TITLE
read length

### ISSUE THREAD

**Issue by ajinkyakhilari** [DMU-lilab/pTrimmer#17]
can the software be used for amplicon sequence size of about 1500bp sequenced through Nanopore sequencing.

**Comment by XLZH** [comment]
I have modified the READ length from 512bp to 2048bp, and now the ptrimmer support for a READ length of  2048bp. Since I don't have Nanopore sequencing datasets, therefore, I can't test the modified code. You can try it, If there is a problem, send me a handful of samples and I will debug for you!

The modified code: https://drive.google.com/file/d/1OdZpcg__tRo-P4TmKIN2S24k0drRW0Gl/view?usp=sharing
