### ISSUE TITLE
pTrimmer producers improperly paired fastQ files

### ISSUE THREAD

**Issue by marchoeppner** [DMU-lilab/pTrimmer#6]
Hi,
I just finished running an existing pipeline, which I extended with pTrimmer to ensure removal of sequencing primers. The resulting data is now unfortunately improperly paired (i.e. the reads in each mate file are no longer synchronous). This probably should not happen as some tools absolutely require properly paired PE data. 

Cheers,
Marc

**Comment by XLZH** [comment]
Hi @marchoeppner ,

Could you please provide one or more read pairs (PE) that could reproduce the problem? Thanks!

Best,
Xiaolong

**Comment by marchoeppner** [comment]
Hi,
I think I have mis-intrepreted the issue, since the QC at the end returned a low value of properly paired reads compared to the original fastQ file. 

But it seems the issue was that the trimming discarded 99% of the reads. Whatever was left, consisted of "NNNNNN". 

The data was created from a set of partially overlapping amplicons , tiled across a viral genome. Is it possible that pTrimmer would somehow have issues with such a setup?

Cheers,
Marc

**Comment by XLZH** [comment]
Hi @marchoeppner ,

It's difficult to decide what's wrong with pTrimmer just by your description.
Please provide some reads and the corresponding amplicon file to me, so that I can debug pTrimmer with them. Thanks!

Best,
Xiaolong

**Comment by marchoeppner** [comment]
Sorry, been a bit busy. Here is a set of FastQ files from an overlapping set of amplicons for COVID19 (see: https://github.com/artic-network/artic-ncov2019/tree/master/primer_schemes/nCoV-2019/V3). 

When I run this with pTrimmer 1.3.0, I get 1.4% of surviving reads only. From aligning the reads against the genome without pTrimmer, everything looks "fine", so I am wondering if something about the way the amplicons are tiled is incompatible with assumptions made by pTrimmer? Or maybe I messed up the pTrimmer adapter file (?).

https://www.dropbox.com/s/e790at136p7ffjp/sample_R1.fastq.gz?dl=0
https://www.dropbox.com/s/e790at136p7ffjp/sample_R1.fastq.gz?dl=0
[ARTIC-v3_ptrimmer.txt](https://github.com/DMU-lilab/pTrimmer/files/4804284/ARTIC-v3_ptrimmer.txt)

**Comment by XLZH** [comment]
Hi @marchoeppner ,

pTrimmer is designed to trim off primer sequence of amplicon fastq files.

Therefore, it assumes that each read at least has a primer sequence at the start of read(5'-end), otherwise, the read will be considered as invalid read.

For the fastq and primer files you provided, I choose some primer sequences and search them in the fastq file, and find the primer sequences (you defined) anywhere on the read.

So I guess your sample fastq file is not amplified from your primer sequence. Perhaps WGS, WES or some other sequencing strategy.  If NOT, please provide some reads and their corresponding primer sequence, which was failed to be trimmed by pTrimmer, thanks.

Best,
Xiaolong
